name: projetctv0
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  cloud_firestore: ^5.5.0
  file_picker: ^8.1.4
  firebase_core: ^3.8.0
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.18.0
  fluttertoast: ^8.2.8
  firebase_auth: ^5.3.4
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
